name: End-to-end tests
on:   
  push: 
  workflow_dispatch: 

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Configurar Java (necessário para Allure)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Especifica a distribuição do JDK

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Baixar histórico do GitHub Pages
      - name: Download Allure History from GitHub Pages
        run: |
          mkdir -p allure-results/history
          wget -q --show-progress https://tiagotaq.github.io/teste-allure-novo-pacote/history/categories-trend.json -O allure-results/history/categories-trend.json
          wget -q --show-progress https://tiagotaq.github.io/teste-allure-novo-pacote/history/duration-trend.json -O allure-results/history/duration-trend.json
          wget -q --show-progress https://tiagotaq.github.io/teste-allure-novo-pacote/history/history-trend.json -O allure-results/history/history-trend.json
          wget -q --show-progress https://tiagotaq.github.io/teste-allure-novo-pacote/history/history.json -O allure-results/history/history.json
          wget -q --show-progress https://tiagotaq.github.io/teste-allure-novo-pacote/history/retry-trend.json -O allure-results/history/retry-trend.json
        continue-on-error: true

      # Executar os testes com Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v5
        continue-on-error: true

      - name: Verificar se allure-results foi gerado
        run: |
          ls -la allure-results

      # Gerar o relatório Allure
      - name: Generate Allure Report
        run: npx allure generate allure-results --clean

      # Publicar os relatórios Allure como artefato
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      # Publicar os relatórios em GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report